# -*- coding: utf-8 -*-
"""T5_Base_Model_for_Summarization,_Sentiment_Classification,_and_Translation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WnXggpHHpt6-v-eQz_AEx5dunnc4CVic

# Introduction to T5 Model for Text-to-Text Tasks

 This notebook demonstrates the use of the T5 (Text-To-Text Transfer Transformer) model from the Hugging Face Transformers library for various natural language processing tasks, including summarization, translation, and sentiment analysis. T5 frames all NLP problems as a text-to-text task, where the input and output are always text strings.

 This demonstration is inspired by and adapted from the PyTorch Text T5 Demo tutorial: [https://docs.pytorch.org/text/stable/tutorials/t5_demo.html](https://docs.pytorch.org/text/stable/tutorials/t5_demo.html)
"""



from transformers import T5Tokenizer , T5ForConditionalGeneration

"""### Import T5 Tokenizer and Model

This cell imports the `T5Tokenizer` and `T5ForConditionalGeneration` classes from the `transformers` library. These are essential for loading the pre-trained T5 model and its corresponding tokenizer.
"""

import torch

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model_name = "t5-base"

tokenizer = T5Tokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

model.to(device)

"""### Load T5 Model and Tokenizer

This cell initializes the T5 tokenizer and model. It also checks for GPU availability and moves the model to the GPU if one is present, which significantly speeds up computation. The `t5-base` model is loaded, which is a pre-trained version of T5.
"""

text = """
Artificial Intelligence is transforming industries
through automation, deep learning, and generative models.
Large language models can understand and generate human-like text.
"""

input_text = "summarize: " + text

"""### Prepare text for summarization

This markdown cell sets up an example text for summarization. The input is prefixed with `"summarize: "` to instruct the T5 model to perform a summarization task.
"""

inputs = tokenizer.encode(
    input_text,
    return_tensors="pt",
    max_length=512,
    truncation=True
).to(device)


summary_ids = model.generate(
    inputs,
    max_length=150,
    min_length=40,
    length_penalty=2.0,
    num_beams=4,
    early_stopping=True
)

summary = tokenizer.decode(
    summary_ids[0],
    skip_special_tokens=True
)

print(summary)

"""### Generate summary

This cell tokenizes the input text and then uses the T5 model to generate a summary. The `model.generate()` function is called with parameters to control the length, beam search, and early stopping of the summary generation. Finally, the generated summary is decoded and printed.
"""

text = "Hello, how are you?"

input_text = "translate English to French: " + text

"""### Prepare text for translation

This cell prepares an English sentence for translation into French. The input is prefixed with `"translate English to French: "` to specify the translation task.
"""

inputs = tokenizer.encode(
    input_text,
    return_tensors="pt",
    max_length=512,
    truncation=True
).to(device)

outputs = model.generate(inputs)

translated = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print(translated)

"""### Generate translation

This cell tokenizes the English input text and then uses the T5 model to translate it into French. The translated output is then decoded and printed.
"""

text = "This movie was fantastic and emotional."

input_text = f"sst2 sentence: {text}"

"""### Prepare text for sentiment analysis

This cell prepares a sentence for sentiment analysis using the SST-2 (Stanford Sentiment Treebank) task. The input is prefixed with `"sst2 sentence: "` to indicate the sentiment analysis task.
"""

inputs = tokenizer.encode(
    input_text,
    return_tensors="pt"
).to(device)

outputs = model.generate(inputs)

preds = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print(preds)

"""### Generate sentiment prediction

This cell tokenizes the input sentence and uses the T5 model to predict its sentiment. The predicted sentiment (e.g., "positive" or "negative") is then decoded and printed.
"""



"""### Create a Gradio Interface"""

import gradio as gr

def t5_inference(task_type, text):
    """
    Performs T5 model inference for various NLP tasks.
    """
    if task_type == "Summarization":
        input_text = "summarize: " + text
    elif task_type == "Translation (English to French)":
        input_text = "translate English to French: " + text
    elif task_type == "Sentiment Analysis (SST-2)":
        input_text = "sst2 sentence: " + text
    else:
        return "Invalid task type selected."

    inputs = tokenizer.encode(
        input_text,
        return_tensors="pt",
        max_length=512,
        truncation=True
    ).to(device)

    # Generate outputs based on the task
    if task_type == "Summarization":
        output_ids = model.generate(
            inputs,
            max_length=150,
            min_length=40,
            length_penalty=2.0,
            num_beams=4,
            early_stopping=True
        )
    else:
        output_ids = model.generate(inputs)

    result = tokenizer.decode(
        output_ids[0],
        skip_special_tokens=True
    )
    return result

"""### Generic Translation UI for Multiple Languages"""

def translate_any_to_any(source_lang, target_lang, text):
    """
    Translates text between specified source and target languages using the T5 model.
    """
    # T5 expects the input in the format 'translate <source_lang> to <target_lang>: <text>'
    input_text = f"translate {source_lang} to {target_lang}: {text}"

    inputs = tokenizer.encode(
        input_text,
        return_tensors="pt",
        max_length=512,
        truncation=True
    ).to(device)

    outputs = model.generate(inputs)

    translated = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )
    return translated

supported_languages = ["English", "French", "German", "Romanian", "Spanish", "Portuguese", "Italian", "Dutch", "Arabic", "Japanese", "Korean", "Turkish", "Swedish", "Norwegian", "Czech", "Croatian", "Persian"]

multi_lang_translation_interface = gr.Interface(
    fn=translate_any_to_any,
    inputs=[
        gr.Dropdown(choices=supported_languages, label="Source Language", value="English"),
        gr.Dropdown(choices=supported_languages, label="Target Language", value="French"),
        gr.Textbox(lines=5, label="Text to Translate")
    ],
    outputs=gr.Textbox(label="Translated Text"),
    title="Multi-Language Translator Football WC edition (Powered by T5)",
    description="Translate text between a wider range of languages using the T5 model."
)
multi_lang_translation_interface.launch(share=True)
